### ISSUE TITLE
scroll getting stuck when moving scrollwheel down for first time

### ISSUE THREAD

**Issue by SurajMeena** [ritmillio/next-reveal#4] opened 2023-10-01 14:07 UTC
<img width="125" alt="image" src="https://github.com/ritmillio/next-reveal/assets/34710254/9a39dd4e-76a8-4ef3-b034-5636000a3ca9">
The above image highlights the issue pretty well and I have observed this to be the case only when I am using origin="bottom"
My code looks something like this 
<img width="707" alt="image" src="https://github.com/ritmillio/next-reveal/assets/34710254/2ae0cfd0-fb2c-44d3-9696-a38cdac7ed4d">
Please let me know if I am using the wrapper in a wrong way

**Comment by ritmillio** [comment] 2023-10-03 16:25
Hey, @SurajMeena . Sorry for the later response.. Your example looks okay to me. I tried to reproduce the bug on my end but I wasn't able to.. I even tested it in multiple browsers(Brave, Arc, Safari). My suggestion would be to try to wrap a simple div and add elements one-by-one therefor you might be able to figure out if there's any css/Element issue is behind. Let me know if you figured out what caused the issue on your end.

**Comment by ritmillio** [comment] 2023-10-20 18:57
Since I haven't received any more issues connected to this I will close this issue for now..

**Closed as completed by ritmillio** 2023-10-20 18:57 UTC
